softdepend: [CloudNetAPI]

name: LobbySystem
version: B1.0
author: PixelTeleV

main: ch.PixelTV.Main.Main

commands:
  gm:
    description: GameMode Command
    aliases: [gamemode]
  build:
    description: Build Command
  fly:
    description: Fly Command
  rank:
    description: Rank Command